### ISSUE TITLE
Node 12 Dependency error

### ISSUE THREAD

**Issue by jmpicnic** [anvil-open-software/wuf#70]
It seems that when running Node 12, on OSX, the command "yarn start" throws an error regarding an incompatible library version. See below. Once I installed Node 11 it worked fine. I think the node-sass dependency needs to be upgraded to 4.12, but it is buried in an angular library and I did not want to touch anything in there. Otherwise I would have created a pull request.

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (/Users/jmp/crux/code/client/wuf/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/jmp/crux/code/client/wuf/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/jmp/crux/code/client/wuf/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadLoader (/Users/jmp/crux/code/client/wuf/node_modules/loader-runner/lib/loadLoader.js:18:17)

**Comment by luvaas** [comment]
Node-sass is a dependency of just about anything that needs sass/scss compilation, including Angular.  However, it looks like an older version of node-sass is declared as a dependency of wuf-web-message, so updating it there may fix this issue.

**Comment by luvaas** [comment]
https://github.com/anvil-open-software/wuf/issues/71

**Comment by jmpicnic** [comment]
Thanks
